# Generated by Django 5.1.1 on 2024-11-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
    ]
