# Generated by Django 5.0.7 on 2024-11-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_semester_rename_mark_result_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
