# Generated by Django 5.0.7 on 2024-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_subject_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
