# Generated by Django 5.0.7 on 2024-11-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_subject_credit_alter_subject_credit_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
