# Generated by Django 5.1.1 on 2024-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_result_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='semester_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
